inherit_from: .rubocop_todo.yml

---
inherit_gem:
  gc_ruboconfig: rubocop.yml

# Set this to be the oldest supported version of Ruby for this library. See
# COMPATIBILITY.md for our compatibility and deprecation policy.
AllCops:
  TargetRubyVersion: 2.4

Metrics/MethodLength:
  Max: 15

Style/RescueStandardError:
  Exclude:
    - "*/**/*_spec.rb"

# Maximum example length: the default is very restrictive
RSpec/ExampleLength:
  Max: 15

# Default is very restrictive
RSpec/MultipleExpectations:
  Max: 3

# Several stdlib classes won't support the human-readable predicate names
# rubocop wants you to use, so auto-correct will cause errors. Disable these
# checks.
Style/ZeroLengthPredicate:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    # These are the default allowed names, set by Rubocop
    - io
    - id
    # These are some custom names that we want to allow, since they aren't
    # uncommunicative - they're actually rather meaningful!
    - as
    # This is our increment kwarg for Prometheus metrics
    - by
